// Les 15 jours du carnet de route, portés depuis le PDF « Chine — 11-26 septembre 2026 (v8) ».
// Chaque étape : t = heure de Pékin en "HH:MM" (null si l'horaire est flou), label = ce qui s'affiche,
// tag = pastille colorée (voir TAGS dans data.js). L'id sert à cocher l'étape et doit rester stable.
export const DAYS = [
  {
    n: 1, date: "2026-09-12", dow: "Samedi 12 septembre", city: "Shanghai",
    title: "Atterrissage, et le Bund au crépuscule",
    stats: [["Arrivée", "9 h 25"], ["Terminal", "Pudong T1"], ["Nuits ici", "3"], ["Décalage", "+6 h"]],
    tips: [{ title: "Le compte du premier jour", text: "Décollage de Luxembourg à 10 h 45 le 11, correspondance de trois heures à Schiphol, douze heures et quart de vol, atterrissage à 9 h 25 le 12. Vous aurez une nuit courte dans l'avion et une journée entière devant vous — d'où un programme volontairement léger : marcher, regarder, manger, dormir." }],
    items: [
      { id: "d1a", t: "09:25", title: "Arrivée à Shanghai Pudong, terminal 1", tag: "VOL", text: "Vol KL895. Passeport valide 6 mois, confirmation du retour imprimée, fiche d'arrivée remplie dans l'avion. File « Foreigners », empreintes, puis douane." },
      { id: "d1b", t: "10:30", title: "Rejoindre Jing'an", text: "Le Maglev file à 430 km/h jusqu'à Longyang Road en 7 minutes, puis métro ligne 2. Sinon un Didi direct : 50 à 60 min, autour de 200 CNY. Retirer 500 CNY au distributeur de l'aéroport." },
      { id: "d1c", t: "12:00", title: "Waiting Century Hotel", tag: "RÉSERVÉ", text: "1088 Chang'an Road, Jing'an, à côté de la gare de Shanghai — métro lignes 1, 3 et 4. Enregistrement seulement après 14 h : déposer les valises à la consigne et sortir. La réception est ouverte 24 h/24 et déclare automatiquement votre présence à la police, ce qui est obligatoire." },
      { id: "d1d", t: "14:00", title: "Le Bund à pied", text: "Métro ligne 2 jusqu'à Nanjing East Road. La promenade du Waitan longe le Huangpu : d'un côté les façades des concessions, de l'autre la skyline de Pudong." },
      { id: "d1e", t: "18:30", title: "Un verre au Condé Bar", tag: "LISTE DE MIRINA", text: "Regent Shanghai on the Bund, 60 Huangpu Road, Hongkou — à l'extrémité nord du Bund, près du pont Waibaidu. Terrasse plein cadre sur Pudong : les tours s'allument pendant que vous buvez. Réserver, surtout un samedi soir." },
      { id: "d1f", t: "20:00", title: "Xiaolongbao et dodo", text: "Les raviolis à la soupe sont une spécialité de Shanghai, pas une spécialité chinoise générique. Ne pas lutter contre le décalage : six heures d'avance se paient le lendemain." },
    ],
  },
  {
    n: 2, date: "2026-09-13", dow: "Dimanche 13 septembre", city: "Shanghai",
    title: "Le marché fantôme à l'aube, puis les vitrines",
    stats: [["Le matin", "Cangbao Lou"], ["Puis", "Huawei & DJI"], ["Le soir", "Shanghai Tower"], ["Marche", "Beaucoup"]],
    tips: [{ title: "L'Osmo Action 6 : l'écart de prix est mince", text: "Lancée en Chine à 2 998 CNY, soit environ 366 €, contre 379 € conseillés en Europe pour le combo standard. L'écart tient dans un repas et s'inverse à la première promotion française.\n\nLa vraie raison d'acheter au magasin amiral, c'est de la prendre en main d'abord. En revanche : garantie chinoise, pas de rétractation européenne, et demandez en boutique si l'appareil du marché chinois s'apparie avec l'application DJI Mimo internationale. Batteries en cabine au retour." }],
    items: [
      { id: "d2a", t: "07:00", title: "Cangbao Lou, le marché aux puces", tag: "DIMANCHE SEULEMENT", text: "457 Fangbang Zhong Lu. Quatre étages de brocanteurs et des étals sauvages le week-end — l'essentiel se vend avant 9 h, d'où le nom de « marché fantôme ». Affiches de propagande, porcelaine, bric-à-brac maoïste. Dongtai Road, que citent les vieux guides, a été démoli." },
      { id: "d2b", t: "09:00", title: "Yuyuan, le temple et le pont", tag: "LISTE DE MIRINA", text: "À dix minutes à pied. Jardin Ming de 1577, minuscule et dense, puis le temple Chenghuang — celui du dieu de la ville — et le pont aux neuf coudes, dont les angles droits sont censés empêcher les mauvais esprits de suivre. Le bazar devient impraticable à partir de 10 h : enchaîner tôt." },
      { id: "d2c", t: "11:30", title: "Huawei, 233 Nanjing East Road", tag: "SUR VOTRE LISTE", text: "Le magasin amiral, sortie 2 du métro Nanjing East Road, 10 h – 22 h. Tout l'écosystème est là. À savoir : les téléphones vendus en Chine n'ont ni services Google ni Play Store et tournent sur HarmonyOS chinois." },
      { id: "d2d", t: "13:00", title: "Déjeuner chez Da Hu Chun · 大壶春", tag: "LISTE DE MIRINA", text: "136 rue du Sichuan Centre, à dix minutes du magasin Huawei. Maison de shengjianbao ouverte en 1932, Bib Gourmand : fond croustillant, farce dense, pas de bouillon qui gicle. Se mange dès l'assiette posée. Self-service, 8 h – 21 h." },
      { id: "d2e", t: "14:00", title: "Métro vers Xintiandi", text: "Ligne 10, deux arrêts." },
      { id: "d2f", t: "14:30", title: "DJI, Madang Road, Xintiandi", tag: "SUR VOTRE LISTE", text: "Le magasin amiral chinois, sur deux niveaux, ouvert de 10 h à 22 h. C'est là que vous prendrez l'Osmo Action 6 — et surtout que vous pourrez la manipuler avant, avec les objectifs et les fixations posés sur le comptoir." },
      { id: "d2g", t: "17:00", title: "Pudong et la Shanghai Tower", text: "632 m, deuxième tour du monde. L'ascenseur monte au 118e en moins d'une minute. Fin d'après-midi pour attraper le jour et la nuit dans la même montée." },
      { id: "d2h", t: "20:00", title: "Croisière sur le Huangpu", tag: "OPTION", text: "Une heure entre les deux rives illuminées, départs toutes les 30 min depuis le Bund." },
    ],
  },
  {
    n: 3, date: "2026-09-14", dow: "Lundi 14 septembre", city: "Shanghai",
    title: "Disneyland Shanghai, une journée entière",
    stats: [["Billet", "Déjà émis"], ["Ouverture", "≈ 8 h 30"], ["Trajet", "40 min"], ["Format", "Journée"]],
    tips: [{ title: "Deux réflexes qui changent la journée", text: "Téléchargez l'application Shanghai Disney Resort avant de partir et liez-la à votre billet : c'est elle qui donne les temps d'attente en direct, les réservations de restaurant et l'accès aux files payantes. Elle marche sans VPN.\n\nLe parc n'ouvre officiellement qu'à 8 h 30, mais les portiques laissent souvent entrer un quart d'heure plus tôt. Un lundi de septembre hors vacances scolaires chinoises, arriver à 8 h suffit largement à faire TRON avant que la file ne dépasse la demi-heure." }],
    items: [
      { id: "d3a", t: "07:30", title: "Départ de l'hôtel", text: "Métro ligne 2 depuis Jing'an jusqu'à Longyang Road, puis ligne 11 jusqu'au terminus Disney Resort. Environ 40 à 50 min, sans changement compliqué." },
      { id: "d3b", t: "08:30", title: "Aux portes à l'ouverture", tag: "PASSEPORT", text: "Le billet est nominatif : c'est le passeport qu'on scanne à l'entrée, comme partout en Chine. Un lundi de septembre hors vacances scolaires chinoises est le meilleur créneau possible — profitez-en." },
      { id: "d3c", t: "09:00", title: "Les attractions à faire en premier", text: "Le château est le plus grand des parcs Disney et abrite une attraction, ce qui n'existe nulle part ailleurs. TRON Lightcycle Power Run et les Pirates des Caraïbes version Shanghai sont les deux pièces uniques du parc : les faire dès l'ouverture." },
      { id: "d3d", t: "12:30", title: "Déjeuner", text: "Réserver une table via l'application du parc en arrivant le matin, sinon c'est file d'attente et nouilles debout." },
      { id: "d3e", t: "19:00", title: "Le spectacle du soir", text: "Illuminations sur le château, puis retour par la ligne 11." },
      { id: "d3f", t: "21:30", title: "Retour à Jing'an", text: "Dernier métro largement suffisant, la ligne 11 roule tard." },
    ],
  },
  {
    n: 4, date: "2026-09-15", dow: "Mardi 15 septembre", city: "Chongqing",
    title: "Cap à l'ouest : Chongqing, la ville verticale",
    stats: [["Vol", "3U8972"], ["PVG T2", "11 h 05"], ["CKG T3", "13 h 50"], ["Hôtel", "58e étage"]],
    tips: [{ title: "Hongyadong s'allume à la nuit tombée", text: "Les lumières s'allument vers 19 h 30 et le site reste ouvert jusqu'à 23 h, gratuitement." }],
    items: [
      { id: "d4a", t: "11:05", title: "Vol Shanghai Pudong T2 → Chongqing Jiangbei T3", tag: "RÉSERVÉ", text: "Départ de l'hôtel à 8 h : le vol part de Pudong, terminal 2, une heure depuis Jing'an par la ligne 2. Sichuan Airlines, Airbus A320, 2 h 45 de vol, repas servi. Arrivée à 13 h 50." },
      { id: "d4b", t: "15:00", title: "SEYA Panoramic Hotel, Jiefangbei", tag: "RÉSERVÉ", text: "Métro ligne 10 depuis l'aéroport, environ 45 min. L'hôtel occupe le 58e étage du Yingli International Financial Center, 28 Minquan Road, en plein Yuzhong : Hongyadong à pied, Liziba à cinq minutes de métro. Enregistrement à partir de 14 h, réception 24 h/24, et un service de transfert existe si vous préférez éviter le métro avec les valises." },
      { id: "d4c", t: "16:30", title: "Jiefangbei et la rue Bayi", tag: "VOTRE LISTE", text: "La rue piétonne commence en bas de votre tour. Juste à côté, la 八一好吃街 — « la bonne rue à manger de Bayi » — est un couloir de néons et d'échoppes : brochettes, xiaotangyuan, tofu, poulet bobo. On y grignote debout, on n'y dîne pas." },
      { id: "d4d", t: "18:00", title: "L'Œil des Nuages · 云端之眼", tag: "INCLUS", text: "67e étage du Union International Building, 201 Xinhua Road — dix minutes à pied. La plus haute terrasse à ciel ouvert de la ville, à 520 m, avec sa coursive circulaire et son escalier en spirale rouge. 68 CNY l'entrée, moins 22 % avec votre réservation d'hôtel, un billet par jour.\n\nArriver une heure avant le coucher du soleil : vous aurez l'heure dorée, la nuit, et les néons qui s'allument." },
      { id: "d4e", t: "19:45", title: "Hongyadong illuminé", text: "Les lumières s'allument vers 19 h 30 et le site reste ouvert jusqu'à 23 h, gratuitement. Le meilleur point de vue n'est pas dedans mais en face : pont Qiansimen, ou Nanbin Road sur la rive sud." },
      { id: "d4f", t: "20:45", title: "井到吃老火锅, puis 面壁糖水", tag: "LISTE DE MIRINA", text: "Le hot pot de quartier, rue Linjiang, ruelle Dajing — à dix minutes à pied. Suif de bœuf et poivre du Sichuan : ça engourdit avant de brûler. Demandez un yuanyang, la marmite séparée moitié épicée. Puis 面壁糖水, deux portes plus loin au n° 12 : les desserts glacés qui éteignent l'incendie." },
      { id: "d4g", t: "22:00", title: "Shibati et Deyi World, illuminés", tag: "LISTE DE MIRINA", text: "十八梯 commence au bout de la même rue : les escaliers de pierre du vieux Chongqing, restaurés, lanternes allumées. Et à côté, 得意世界 à Jiaochangkou — un canyon d'enseignes au néon entre deux immeubles courbes. Les deux sont gratuits et ouverts tard." },
    ],
  },
  {
    n: 5, date: "2026-09-16", dow: "Mercredi 16 septembre", city: "Chongqing",
    title: "Le métro qui traverse un immeuble, et un barbecue sur la colline",
    stats: [["Secteur", "Yuzhong"], ["Déplacements", "Métro"], ["Le soir", "Zhang San BBQ"], ["Marche", "Soutenue"]],
    tips: [
      { title: "Le barbecue : viser 19 h 30, pas plus tard", text: "L'endroit est viral, il n'y a pas de réservation en ligne pour les étrangers, et la file se forme avant le coucher du soleil. Arriver tôt laisse le temps de s'installer et de voir les lumières s'allumer une à une. Le spectacle de drones au-dessus du fleuve est le samedi uniquement : vos trois jours tombent du mardi au jeudi, vous ne l'aurez pas." },
      { title: "Ce qui reste hors programme", text: "Cette journée boucle toute la liste de Mirina côté Chongqing, sauf The Ring et le temple Hong'en — voir la page « Chongqing à la carte »." },
    ],
    items: [
      { id: "d5a", t: "07:45", title: "Petit-déjeuner chez Gui Baozi · 鬼包子", tag: "LISTE DE MIRINA", text: "八一路238号, premier niveau de la place Bayi — à cinq minutes de l'hôtel. Baozi vapeur autour de 2 €, baozi frits et lait de soja pour 3 €. La file est longue mais elle avance vite." },
      { id: "d5b", t: "08:30", title: "Station Liziba", tag: "VOTRE LISTE", text: "La ligne 2 traverse un immeuble d'habitation au sixième étage. Plateforme d'observation gratuite, ouverte de 6 h 30 à 22 h 30. Avant 9 h, sinon la file pour la photo." },
      { id: "d5c", t: "10:00", title: "Raffles City et le Sky Bridge", tag: "VOTRE LISTE", text: "À la pointe de la péninsule : une passerelle de verre suspendue entre quatre tours, 250 m au-dessus du confluent. La meilleure leçon de géographie que Chongqing puisse donner." },
      { id: "d5d", t: "11:30", title: "Temple Luohan", tag: "VOTRE LISTE", text: "Coincé entre les tours : 500 statues d'arhats alignées dans la pénombre, chacune avec un visage différent. Court, saisissant, et à deux pas de Jiefangbei." },
      { id: "d5e", t: "12:30", title: "花市豌杂面 · Hua Shi Pea Noodles", tag: "LISTE DE MIRINA", text: "85 rue Minsheng, à cinq minutes du temple. Nouilles aux pois cassés et wontons — le déjeuner local par excellence, rapide et léger, parce que la journée est longue et le dîner copieux." },
      { id: "d5f", t: "14:30", title: "Ciqikou et le temple Baolun", tag: "LISTE DE MIRINA", text: "Le vieux bourg de porcelaine, pavés et lanternes rouges. Bondé l'après-midi : s'enfoncer dans les ruelles latérales — et y chercher le temple Baolun (宝轮寺), caché dans les vieilles rues, encens, rubans rouges et pagode dorée. Il est dedans, il ne coûte rien de plus." },
      { id: "d5g", t: "17:00", title: "Téléphérique du Yangtsé, puis Xiahaoli", tag: "VOTRE LISTE", text: "La traversée du fleuve en cabine, deux minutes, au couchant. 8 h – 22 h, environ 4 € l'aller et 7 € l'aller-retour. Il vous dépose sur la rive sud, à deux pas de 下浩里 · Xiahaoli : un quartier ancien accroché à la pente, restauré en boutiques et bars, gratuit, ouvert jusqu'à 21 h." },
      { id: "d5h", t: "19:30", title: "Zhang San BBQ · 张三的烤肉", tag: "SUR VOTRE LISTE", text: "Le barbecue à flanc de colline. Il faut monter à pied les derniers mètres, et c'est ce qui fait tout : on arrive essoufflé devant la skyline entière. Grillades, lanternes dans les arbres, musique live certains soirs.\n\nSon jumeau 丁老头烤肉 · Ding Lao Tou joue exactement la même carte, sur une autre colline. Enregistrer l'adresse sur Amap : un chauffeur Didi ne trouvera pas en alphabet latin." },
    ],
  },
  {
    n: 6, date: "2026-09-17", dow: "Jeudi 17 septembre", city: "Chongqing",
    title: "Le karst de Wulong, ou les grottes de Dazu",
    stats: [["Train", "1 h 30"], ["Site", "UNESCO"], ["Format", "Journée"], ["Retour", "Le soir"]],
    tips: [
      { title: "L'autre option, plus courte et plus calme", text: "Les sculptures rupestres de Dazu : 50 000 statues bouddhiques taillées entre le IXe et le XIIIe siècle, dont un Bouddha couché de 31 m. À 1 h de train, entrée ≈ 15 €, ouvert de 8 h 30 à 18 h. Une demi-journée suffit, et il y a dix fois moins de monde qu'à Wulong.\n\nWulong pour le paysage, Dazu pour la sculpture et une après-midi libre. Il existe une troisième voie, plus ambitieuse : Wulong le jour puis Chiyou Jiuli City le soir, sur la même ligne — voir la page « Les choix à faire »." },
      { title: "Appeler pour le spa depuis le train", text: "Pensez au spa depuis le train du retour. Il se réserve deux heures à l'avance et vous n'y avez droit qu'une fois : un appel vers 19 h, et la soirée est bouclée." },
    ],
    items: [
      { id: "d6a", t: "07:30", title: "Chongqing Est → Wulong", tag: "TRAIN", text: "Environ 1 h 30 de TGV, puis navette vers le parc. Billet à prendre avec les autres trajets, dès le 3 septembre." },
      { id: "d6b", t: "10:00", title: "Les Trois Ponts Naturels", text: "Trois arches calcaires de plus de 200 m, creusées par la rivière, alignées dans un canyon. On descend au fond par ascenseur puis on marche entre les ponts. Entrée ≈ 20 €, site ouvert de 9 h à 16 h — la dernière entrée est tôt, ne traînez pas au déjeuner." },
      { id: "d6c", t: "13:30", title: "Gorge de Longshuixia", text: "Une faille étroite parcourue par des passerelles, dans la brume et les embruns. Compter 2 h. Chaussures qui tiennent, ça glisse." },
      { id: "d6d", t: "17:00", title: "Retour sur Chongqing", text: "Dernier train en fin d'après-midi — vérifier l'horaire le matin même." },
      { id: "d6e", t: "20:00", title: "Le hot pot sérieux", text: "Dernière soirée à Chongqing : c'est le moment du vrai. Les adresses locales servent la marmite jiuge à neuf cases, un bouillon unique très épicé et une huile de sésame à l'ail pour tremper. Demandez weila (微辣) si vous voulez survivre." },
      { id: "d6f", t: "22:00", title: "Expérience Spa Tempête", tag: "INCLUS", text: "Comprise dans la chambre, pour deux, une seule fois pour tout le séjour. Elle se passe dans l'hôtel, le bon se retire à la réception, et le créneau court jusqu'à minuit.\n\nÀ réserver 2 h à l'avance · +86 23 6330 6800" },
    ],
  },
  {
    n: 7, date: "2026-09-18", dow: "Vendredi 18 septembre", city: "Chengdu",
    title: "Une heure de train et tout ralentit",
    stats: [["Train", "1 h 15"], ["Hôtel", "Hidden House"], ["Quartier", "Kuanzhai"], ["Le soir", "Opéra"]],
    tips: [],
    items: [
      { id: "d7a", t: "09:00", title: "Chongqing → Chengdu Est", tag: "TRAIN", text: "1 h 15 de TGV, une des lignes les plus fréquentées du pays : environ 150 trains par jour, on prend le suivant si on rate le sien." },
      { id: "d7b", t: "11:00", title: "The Hidden House · 隐栖堂", tag: "RÉSERVÉ", text: "Kuanzhai Alley, station de métro People's Park. Une chambre avec cour privée et baignoire japonaise, en plein cœur historique — vous n'aurez pas besoin du métro de la semaine." },
      { id: "d7c", t: "14:00", title: "Kuanzhai Xiangzi, à votre porte", text: "« Les ruelles large et étroite » : trois allées Qing restaurées, cours intérieures, salons de thé. Reconstitué, mais joliment — et vous logez dedans." },
      { id: "d7d", t: "16:00", title: "Parc du Peuple, maison de thé Heming", text: "Le rituel de Chengdu : thé au jasmin en terrasse, cartes, et si vous osez, le nettoyage d'oreilles au diapason. Deux heures s'y passent sans qu'on les voie." },
      { id: "d7e", t: "19:30", title: "Opéra du Sichuan", tag: "À RÉSERVER", text: "Shufengyayun, à dix minutes à pied. Le bian lian, le changement de visage : les masques tombent plus vite que l'œil ne suit, et personne n'a jamais expliqué comment. Plus cracheurs de feu et comédie. 148 CNY, salle ouverte de 10 h à 22 h." },
    ],
  },
  {
    n: 8, date: "2026-09-19", dow: "Samedi 19 septembre", city: "Chengdu",
    title: "Les pandas, et pas plus tard que 7 h 30",
    stats: [["Ouverture", "7 h 30"], ["Sur place", "3 – 4 h"], ["Entrée", "55 CNY"], ["Réserver", "Le 5 sept."]],
    tips: [{ title: "C'est un samedi", text: "La base est prise d'assaut le week-end, et le quota journalier part vite. Réserver le 5 septembre, jour d'ouverture des ventes, et viser le tout premier créneau. Une entrée à 10 h un samedi, c'est une file d'attente devant des pandas endormis." }],
    items: [
      { id: "d8a", t: "06:45", title: "Départ de l'hôtel", text: "La base est à 30 min du centre. Didi plus simple que le métro à cette heure-là." },
      { id: "d8b", t: "07:30", title: "Base de reproduction des pandas géants", tag: "PASSEPORT", text: "Entrer par la porte Sud, la plus proche des nurseries. Créneau du matin obligatoire, réservé au nom du passeport." },
      { id: "d8c", t: "08:00", title: "L'heure où ils sont réveillés", text: "Les petits sont nourris entre 8 h et 9 h 30 ; les adultes bougent jusqu'à 10 h. Après, ils dorment tous et ne se relèveront pas de la journée. Toute la visite se joue là." },
      { id: "d8d", t: "11:00", title: "Le reste du parc", text: "Pandas roux en semi-liberté, musée, bambouseraies. Compter 3 à 4 h pour tout voir sans courir." },
      { id: "d8e", t: "14:30", title: "Chunxi Road, Taikoo Li et IFS", tag: "LISTE DE MIRINA", text: "Le cœur commerçant de Chengdu, tout en un : la rue piétonne 春熙路, les allées basses de Taikoo Li autour du temple Daci, et l'IFS avec son panda géant qui escalade la façade, les fesses dans le vide au-dessus de la rue. C'est la photo de Chengdu." },
      { id: "d8f", t: "18:00", title: "SKP-S, puis le parc Jiaozi la nuit", tag: "LISTE DE MIRINA", text: "Au sud, dans le quartier financier : SKP et son installation de bambous lumineux, ses pandas sculptés à l'entrée du SKP-S — le centre commercial le plus futuriste que vous verrez du voyage. À côté, le parc Jiaozi et ses passerelles courbes qui s'allument en bleu au-dessus de l'eau." },
      { id: "d8g", t: "21:00", title: "Rue Yulin", text: "Bars et petites cantines, le quartier où sortent les Chengdunais eux-mêmes." },
    ],
  },
  {
    n: 9, date: "2026-09-20", dow: "Dimanche 20 septembre", city: "Chengdu",
    title: "La chasse aux trésors, puis dîner en empereur",
    stats: [["Le matin", "Songxianqiao"], ["L'après-midi", "东郊记忆"], ["Le soir", "Shu Yan Fu"], ["Alternatives", "Trois"]],
    tips: [{ title: "Trois façons de remplacer la journée", text: "Leshan · le Grand Bouddha de 71 m taillé dans la falaise, 1 h de TGV. Spectaculaire et fatigant : train, bus, escaliers, foule du dimanche.\n\nDujiangyan · le système d'irrigation millénaire (80 CNY, 8 h – 22 h), le mont Qingcheng (80 CNY, 8 h – 17 h 30) et la librairie Zhongshuge aux plafonds de miroirs sont tous les trois au même endroit, à 1 h de train. La meilleure journée hors de la ville.\n\nLuodai · un bourg hakka millénaire à l'est, gratuit, une demi-journée.\n\nAttention : Leshan et Dujiangyan vous ramènent trop tard pour le service de 18 h 30 chez Shu Yan Fu. Seuls Songxianqiao et Luodai laissent la soirée intacte." }],
    items: [
      { id: "d9a", t: "09:00", title: "Marché de Songxianqiao", tag: "SHOPPING", text: "送仙桥古玩市场, le plus grand marché d'antiquités de l'ouest de la Chine, ouvert depuis 1998. Jade, porcelaine, théières d'Yixing, calligraphie, sculptures sur bois. Entrée libre.\n\nSept pièces sur dix sont des reproductions — les locaux le disent eux-mêmes. Négociez au tiers du prix annoncé, en souriant." },
      { id: "d9b", t: "13:00", title: "Déjeuner et sieste", text: "Mapo doufu, dan dan mian, poulet gong bao — tous nés dans un rayon de 200 km. Puis rien : Chengdu est la ville où l'on a le droit de ne rien faire." },
      { id: "d9c", t: "15:00", title: "东郊记忆 · Eastern Suburb Memory", tag: "LISTE DE MIRINA", text: "Une ancienne usine électronique des années 1950, dans le district de Chenghua, transformée en friche créative : briques rouges, cheminées, galeries, cafés, salles de concert. Le contraire exact de Kuanzhai — et c'est là que vit la jeunesse de Chengdu." },
      { id: "d9d", t: "18:30", title: "蜀宴赋 · Shu Yan Fu, dîner en empereur", tag: "À RÉSERVER", text: "Et il est dans l'Eastern Suburb Memory : vous n'avez pas à bouger. Un banquet immersif de 98 minutes sous projections à 360°, avec danses, et des comédiens qui incarnent l'empereur Han Wudi, le poète Li Bai et Yang Guifei et viennent vous parler à table.\n\nHanfu, coiffure et maquillage sont fournis par une équipe sur place — c'est ici que vous aurez votre costume, en meilleur décor qu'ailleurs. Service du soir à 18 h 30." },
    ],
  },
  {
    n: 10, date: "2026-09-21", dow: "Lundi 21 septembre", city: "Xi'an",
    title: "Sous les monts Qinling, jusqu'à Xi'an",
    stats: [["Train", "3 h 30"], ["Hôtel", "Bell Tower"], ["L'après-midi", "Remparts"], ["Le soir", "Huimin Jie"]],
    tips: [{ title: "La ligne franchit les monts Qinling", text: "92 % du trajet en tunnels et sur viaducs, mais les trouées valent la fenêtre côté droit." }],
    items: [
      { id: "d10a", t: "08:30", title: "Chengdu Est → Xi'an Nord", tag: "TRAIN", text: "3 h 10 pour le plus rapide, 4 h en moyenne. La ligne franchit les monts Qinling, la barrière climatique qui sépare la Chine du riz de la Chine du blé : 92 % du trajet en tunnels et sur viaducs, mais les trouées valent la fenêtre côté droit." },
      { id: "d10b", t: "12:30", title: "Elegant Hotel Bell Tower Yongningmen", tag: "RÉSERVÉ", text: "Xi'an Nord est à 20 km du centre : métro ligne 2 jusqu'à la Tour de la Cloche. Votre hôtel est intra-muros, contre la porte Sud — tout ce qui suit se fait à pied." },
      { id: "d10c", t: "15:00", title: "Les remparts à vélo", text: "14 km de muraille Ming, larges de 12 m, intactes tout autour de la vieille ville. Le tour complet prend 1 h 40 à vélo. L'entrée de la porte Sud est à votre porte." },
      { id: "d10d", t: "17:30", title: "Shuyuanmen, la rue des lettrés", tag: "SHOPPING", text: "书院门, juste en bas des remparts côté sud : pinceaux, encre, papier de riz, sceaux gravés à votre nom pendant que vous attendez. C'est ici qu'on achète les vrais souvenirs de Xi'an, pas dans le quartier musulman." },
      { id: "d10e", t: "19:00", title: "Huimin Jie et la Grande Mosquée", text: "La communauté Hui est à Xi'an depuis la route de la Soie. Brochettes d'agneau au cumin, roujiamo au bœuf, nouilles 裤带面 larges comme des ceintures. Touristique et pas toujours le plus authentique — mais c'est là qu'on goûte un peu de tout.\n\nAu milieu du quartier, la Grande Mosquée du VIIIe siècle : pas de dôme, pas de minaret, des cours et des pavillons comme un temple chinois." },
      { id: "d10f", t: "21:00", title: "Tour de la Cloche et Tour du Tambour", text: "Les deux sont au bout de votre rue et c'est de nuit qu'il faut les voir : l'éclairage les transforme. La cubique est la Cloche, celle qui ressemble à une porte est le Tambour." },
    ],
  },
  {
    n: 11, date: "2026-09-22", dow: "Mardi 22 septembre", city: "Xi'an",
    title: "Huit mille soldats, en formation depuis 2 200 ans",
    stats: [["Site", "Mausolée de Qin"], ["Entrée", "120 CNY"], ["Sur place", "5 – 6 h"], ["Billet", "Passeport"]],
    tips: [{ title: "Trois règles à ne pas rater", text: "Le passeport est le billet. Les guichets sur place ont été supprimés : c'est une réservation en ligne au nom réel, et on scanne le passeport au portique. Oublié à l'hôtel = 40 km pour rien.\n\nLa vente ouvre 7 jours avant, à minuit heure de Pékin — soit 18 h en Europe le 15 septembre, pendant que vous serez à Chongqing. Mettez une alarme.\n\n120 CNY, tarif unique, fosses et parc de Lishan compris, navette incluse. Se méfier des revendeurs devant la gare de Xi'an." }],
    items: [
      { id: "d11a", t: "07:30", title: "Départ de Xi'an", text: "Métro ligne 9 jusqu'à Huaqing Pool, puis Didi ou bus local. Sinon le bus touristique 游5 (306) depuis la gare de Xi'an. Compter 1 h de porte à porte." },
      { id: "d11b", t: "08:15", title: "Aux portes avant l'ouverture", text: "Le site ouvre à 8 h 30. Y être en avance ou après 15 h 30 : entre les deux, c'est une marée de drapeaux de groupes." },
      { id: "d11c", t: "08:30", title: "Fosse 1, puis 3, puis 2", tag: "PASSEPORT", text: "La fosse 1 est la grande nef, 6 000 figures en ordre de bataille. La 3 est le poste de commandement. La 2 montre la cavalerie et les archers, et c'est là que sont les pièces exposées de près. Faire les fosses dans cet ordre : la 1 en premier tant qu'elle est vide." },
      { id: "d11d", t: "13:00", title: "Parc de Lishan", text: "Navette gratuite comprise dans le billet. Le tumulus du premier empereur — jamais fouillé — et les chars de bronze, deux quadriges à l'échelle 1/2, les plus belles pièces du site. Attention : une fois sorti des fosses, on n'y revient pas." },
      { id: "d11e", t: "16:30", title: "Huaqing Chi", tag: "OPTION", text: "Les bains impériaux des Tang, sur la route du retour. Court, joli, dispensable si fatigué." },
      { id: "d11f", t: "20:00", title: "Banquet de raviolis", text: "Une spécialité de Xi'an : dix-huit formes de jiaozi à la suite." },
    ],
  },
  {
    n: 12, date: "2026-09-23", dow: "Mercredi 23 septembre", city: "Xi'an",
    title: "La capitale des Tang, et la veste que vous cherchez",
    stats: [["Musée", "Sur créneau"], ["L'après-midi", "Hanfu"], ["Le soir", "Datang"], ["Effort", "Léger"]],
    tips: [],
    items: [
      { id: "d12a", t: "09:00", title: "Musée d'histoire du Shaanxi", tag: "CRÉNEAU", text: "La meilleure collection du pays sur les Han et les Tang : bronzes, fresques de tombes, orfèvrerie de la route de la Soie. Entrée gratuite mais créneau à réserver, et les places partent la veille au soir. La boutique du musée est excellente — bien meilleure que les échoppes du quartier musulman." },
      { id: "d12b", t: "12:00", title: "Da Ci'en et la Grande pagode de l'Oie sauvage", text: "Le temple 大慈恩寺 enserre la pagode : c'est de ses cours qu'on la cadre le mieux. Bâtie en 652 pour abriter les soutras rapportés d'Inde par Xuanzang, sept étages, montée possible." },
      { id: "d12c", t: "13:30", title: "羊肉泡馍 · le pain trempé dans le bouillon d'agneau", tag: "LISTE DE MIRINA", text: "Le plat de Xi'an. On vous sert un pain sec et un bol vide : c'est vous qui déchirez le pain en miettes, puis la cuisine verse le bouillon dessus. Vingt minutes de travail manuel avant de manger — c'est le rituel." },
      { id: "d12d", t: "15:00", title: "Le hanfu, ici et nulle part ailleurs", tag: "SHOPPING", text: "Xi'an est la ville du costume traditionnel : des centaines de boutiques louent et vendent le hanfu autour de la pagode et de Datang Buyecheng, et les Chinoises se promènent en tenue Tang toute la journée. C'est ici que vous trouverez une vraie veste brodée, pas une contrefaçon de survêtement." },
      { id: "d12e", t: "17:00", title: "Joy City Mall", tag: "SHOPPING", text: "大悦城, à deux pas de la pagode. Pop Mart, bubble tea, restauration : la halte de recharge avant la soirée. Le MixC joue le même rôle en plus haut de gamme." },
      { id: "d12f", t: "19:00", title: "Datang Buyecheng, puis Qujiang", text: "La « cité Tang sans nuit » : avenue piétonne reconstituée, entièrement illuminée, spectacles de rue et lanternes. Kitsch assumé et très réussi — le meilleur décor du séjour si vous avez acheté la tenue l'après-midi. Plus loin, le Qujiang Creative Circle prolonge en néons." },
      { id: "d12g", t: null, label: "Variante", title: "Mont Hua", tag: "AU CHOIX", text: "30 min de TGV, journée complète. Une des cinq montagnes sacrées : téléphériques, arêtes, et les fameuses planches clouées dans le vide. À prendre à la place de tout le reste." },
    ],
  },
  {
    n: 13, date: "2026-09-24", dow: "Jeudi 24 septembre", city: "Shanghai",
    title: "Retour sur Shanghai, et deux nuits en hauteur",
    stats: [["Vol", "MU2153"], ["Départ", "10 h 00"], ["Arrivée", "12 h 15"], ["Hôtel", "Grand Hyatt"]],
    tips: [{ title: "Bien joué sur ce vol", text: "Le train Xi'an – Shanghai met six heures et il tombait la veille du week-end férié de la Mi-Automne — c'était le trajet le plus fragile du programme. En prenant l'avion, et à Hongqiao plutôt qu'à Pudong, vous récupérez une demi-journée entière et vous évitez la ruée sur les billets de train." }],
    items: [
      { id: "d13a", t: "07:30", title: "Départ vers Xianyang", text: "L'aéroport est à 40 km au nord-ouest de Xi'an : navette aéroport ou Didi, compter 1 h. Terminal 5." },
      { id: "d13b", t: "10:00", title: "Vol Xi'an → Shanghai Hongqiao T2", tag: "RÉSERVÉ", text: "2 h 15. Hongqiao est en ville, pas à Pudong : c'est un vrai gain de temps sur le train de six heures." },
      { id: "d13c", t: "13:30", title: "Grand Hyatt Shanghai, tour Jin Mao", tag: "RÉSERVÉ", text: "Métro ligne 2 depuis Hongqiao jusqu'à Lujiazui, 40 min. L'hôtel occupe les étages 53 à 87 de la tour Jin Mao : la réception est au 54e, et l'atrium intérieur descend sur 33 étages au-dessus de votre tête." },
      { id: "d13d", t: "15:00", title: "Temple du Bouddha de jade · 玉佛禅寺", tag: "LISTE DE MIRINA", text: "Putuo, vingt minutes de métro. Deux bouddhas de jade rapportés de Birmanie à la fin du XIXe siècle, dans un temple encore en activité — moines, encens, fidèles." },
      { id: "d13e", t: "16:30", title: "Tianan Quanshu · 天安千树", tag: "LISTE DE MIRINA", text: "Le « jardin suspendu de Babylone » de Heatherwick, au bord de la Suzhou Creek : mille arbres plantés au sommet de colonnes de béton. À vingt minutes à pied du temple, et c'est le bâtiment le plus photographié de Shanghai après le Bund." },
      { id: "d13f", t: "19:00", title: "Yuyuan, les lanternes de la Mi-Automne", tag: "CE SOIR PLUTÔT QUE DEMAIN", text: "Yuyuan monte chaque année une fête des lanternes pour la Mi-Automne : installations lumineuses tout au long du pont aux neuf coudes, lunes géantes, défilé de la déesse de la Lune. Elle tourne pendant des semaines — ce soir, la veille, elle est encore respirable. Demain, jour de fête, ce sera une marée humaine." },
      { id: "d13g", t: "21:30", title: "Retour à Lujiazui", tag: "À RÉSERVER", text: "Et réserver le dîner de demain : un vendredi de Mi-Automne, rien ne se trouve à la porte." },
    ],
  },
  {
    n: 14, date: "2026-09-25", dow: "Vendredi 25 septembre", city: "Shanghai",
    title: "La fête de la Mi-Automne, et la pleine lune sur le Bund",
    stats: [["Férié", "Mi-Automne"], ["Foule", "Maximale"], ["Rythme", "Shopping"], ["Le soir", "Le Bund"]],
    tips: [{ title: "La quinzième nuit du huitième mois lunaire", text: "La fête tombe le 15e jour du 8e mois lunaire, c'est-à-dire la nuit de pleine lune. Depuis Lujiazui, la lune se lève derrière Puxi et la skyline s'allume en face : vous logez du bon côté." }],
    items: [
      { id: "d14a", t: null, label: "Toute la journée", title: "中秋节, la fête de la Lune", text: "Deuxième fête du calendrier chinois après le Nouvel An. Réunions de famille, gâteaux de lune, lanternes. Commerces et sites ouverts et bondés ; banques et administrations fermées." },
      { id: "d14b", t: "09:00", title: "Un temple, un jour de fête", tag: "LISTE DE MIRINA", text: "Longhua (龙华寺), le plus ancien de Shanghai, fondé en 242 — ou Jing'an (静安寺), 1 700 ans et des toits d'or au milieu des tours. Un jour de fête, ils sont pleins d'encens, d'offrandes et de familles." },
      { id: "d14c", t: "12:00", title: "Déjeuner chez Wei Xiang Zhai · 味香斋", tag: "LISTE DE MIRINA", text: "14 rue Yandang, Huangpu. Quatre-vingts ans au même endroit, une carte de quatre plats, et des nouilles à la pâte de sésame qui font la réputation de la maison. Bib Gourmand." },
      { id: "d14d", t: "14:30", title: "The Louis, le paquebot de Louis Vuitton", tag: "LISTE DE MIRINA", text: "789 Nanjing West Road, dans le HKRI Taikoo Hui — métro West Nanjing Road, lignes 2, 12 et 13. Trente mètres de haut, une coque monogramme métallique, trois niveaux d'exposition, boutique et café. Ouvert 10 h – 22 h, entrée gratuite mais créneau d'une heure à réserver via le mini-programme WeChat « My LV » — les créneaux de week-end partent vite." },
      { id: "d14e", t: "16:00", title: "La dernière tournée de courses", tag: "SHOPPING", text: "Nanjing West Road pour le haut de gamme, Nanjing East Road pour le sport et les marques chinoises. Et pour le vintage de marque, les friperies de luxe — Golikooo, Aloooooha — sont dans les concessions, à quinze minutes." },
      { id: "d14f", t: "17:00", title: "Acheter des gâteaux de lune", text: "Les yuebing se vendent partout la semaine de la fête. Pâte de lotus et jaune d'œuf salé pour la version classique ; ça se transporte bien en valise." },
      { id: "d14g", t: "19:30", title: "La pleine lune depuis le Bund", text: "La fête tombe le 15e jour du 8e mois lunaire, c'est-à-dire la nuit de pleine lune. Depuis Lujiazui, la lune se lève derrière Puxi et la skyline s'allume en face : vous logez du bon côté." },
      { id: "d14h", t: "21:30", title: "Dîner réservé", text: "Impérativement réservé, depuis la veille." },
    ],
  },
  {
    n: 15, date: "2026-09-26", dow: "Samedi 26 septembre", city: "Retour",
    title: "Retour",
    stats: [["Vol", "AF117"], ["Départ", "Pudong"], ["Puis", "AF4604"], ["Marge", "3 h"]],
    tips: [{ title: "La veille au soir", text: "Vider le solde Alipay si vous l'avez rechargé, garder 100 CNY en liquide pour le trajet, et sortir les batteries de drone et de power bank des valises de soute — elles voyagent en cabine, sans exception.\n\nVérifier aussi que la fiche d'enregistrement de police du dernier hôtel a bien été faite : c'est le seul papier qui puisse être demandé à la sortie." }],
    items: [
      { id: "d15a", t: "07:45", title: "Départ de Lujiazui vers Pudong", text: "Métro ligne 2 directe, 45 min, ou Didi. Prévoir large : c'est le deuxième jour d'un week-end férié et les axes vers l'aéroport saturent." },
      { id: "d15b", t: null, label: "− 3 h", title: "À l'aéroport", text: "Enregistrement, puis détaxe si vous avez dépassé 500 CNY dans un même magasin signalé « Tax Free » — le formulaire se fait tamponner à la douane avant le contrôle de sécurité, pas après." },
      { id: "d15c", t: null, label: "Milieu de journée", title: "AF117 Shanghai → Paris Charles-de-Gaulle", tag: "VOL", text: "Environ 12 h de vol, arrivée en fin d'après-midi. Vérifiez l'heure exacte sur votre réservation : comme AF4604 part le même jour, le décollage de Shanghai est forcément en milieu de journée, ce qui ne laisse aucune marge pour une dernière sortie." },
      { id: "d15d", t: null, label: "Le soir", title: "AF4604 Paris → Luxembourg", tag: "VOL", text: "Environ 1 h de vol, arrivée dans la soirée." },
    ],
  },
];
